image: node:6
clone:
  depth: full
pipelines:
  branches:
    misc-june:
      - step:
          deployment: test
          script:
            - git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git
     