json.partial! @meeting, partial: "api/meetings/meeting", as: :meeting
json.current_week_average_user_emotions @current_week_average_user_emotions
json.current_month_average_user_emotions @current_month_average_user_emotions
json.current_week_average_team_emotions @current_week_average_team_emotions
json.current_month_average_team_emotions @current_month_average_team_emotions
json.emotion_score_percentage_difference @emotion_score_percentage_difference
json.emotion_score_percentage_difference_monthly @emotion_score_percentage_difference_monthly
json.stats_for_week @stats_for_week
json.stats_for_month @stats_for_month
json.my_current_milestones @my_current_milestones, partial: "api/meetings/milestone", as: :milestone
json.habits_percentage_increase_from_previous_week @habits_percentage_increase_from_previous_week
json.habits_percentage_increase_from_previous_month @habits_percentage_increase_from_previous_month
