:queues:
  - default
  - mailers
  - active_storage_purge
  - active_storage_analysis

:schedule:
  notification_batch_job:
    # At 0 and 30 minutes past every hour.
    cron: '0,30 * * * *'
    class: NotificationBatchJob
